field: 778abb42-18bd-447c-99ae-483c775ed3bd
fieldLayouts:
  e65bd1e5-abf6-43e6-a3f0-2fbb329e35c4:
    tabs:
      -
        fields:
          0ba28a66-d3aa-4c97-ad77-8e26087b3d70:
            required: false
            sortOrder: 7
          24bd1247-7ed2-48e8-af76-5b8ffc486ef6:
            required: false
            sortOrder: 1
          3b1b9f85-3554-4b4a-8d39-467bf5e4a35d:
            required: false
            sortOrder: 4
          42ad64e7-b07b-4601-9e6b-2d21bc0fe5d8:
            required: false
            sortOrder: 6
          55c6cb51-defc-4e30-bc18-e524de65b7b7:
            required: false
            sortOrder: 5
          6ee9b9a7-d12d-4c9b-b069-586609cb5ea9:
            required: false
            sortOrder: 3
          8c274864-9cf0-4ef9-b4bd-88da544515ad:
            required: false
            sortOrder: 2
        name: Content
        sortOrder: 1
fields:
  0ba28a66-d3aa-4c97-ad77-8e26087b3d70:
    contentColumnType: boolean
    fieldGroup: null
    handle: narrowWidth
    instructions: ''
    name: 'Narrow Width'
    searchable: true
    settings:
      default: '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  24bd1247-7ed2-48e8-af76-5b8ffc486ef6:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: 'Allows HTML & Twig syntax.'
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  3b1b9f85-3554-4b4a-8d39-467bf5e4a35d:
    contentColumnType: string
    fieldGroup: null
    handle: internalLink
    instructions: ''
    name: 'Internal Link'
    searchable: true
    settings:
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: ''
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  42ad64e7-b07b-4601-9e6b-2d21bc0fe5d8:
    contentColumnType: string
    fieldGroup: null
    handle: linkIcon
    instructions: ''
    name: 'Link Icon'
    searchable: true
    settings:
      optgroups: true
      options:
        -
          default: '1'
          label: None
          value: none
        -
          default: ''
          label: 'Arrow - Left'
          value: arrowLeft
        -
          default: ''
          label: 'Arrow - Right'
          value: arrowRight
        -
          default: ''
          label: 'Arrow - Up'
          value: arrowUp
        -
          default: ''
          label: 'Arrow - Down'
          value: arrowDown
        -
          default: ''
          label: Brochure
          value: brochure
        -
          default: ''
          label: 'Map Pin'
          value: mapPin
        -
          default: ''
          label: News
          value: news
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  55c6cb51-defc-4e30-bc18-e524de65b7b7:
    contentColumnType: string(255)
    fieldGroup: null
    handle: externalLink
    instructions: ''
    name: 'External Link'
    searchable: true
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  6ee9b9a7-d12d-4c9b-b069-586609cb5ea9:
    contentColumnType: text
    fieldGroup: null
    handle: linkLabel
    instructions: ''
    name: 'Link Label'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  8c274864-9cf0-4ef9-b4bd-88da544515ad:
    contentColumnType: text
    fieldGroup: null
    handle: information
    instructions: 'Allows HTML & Twig syntax.'
    name: Information
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: ctaCaption
name: 'CTA Caption'
sortOrder: 6
