field: 778abb42-18bd-447c-99ae-483c775ed3bd
fieldLayouts:
  43071b8b-6243-4eea-b70b-e6122dd5a909:
    tabs:
      -
        fields:
          b28c567f-a9f9-4d96-848b-1de28c643417:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  b28c567f-a9f9-4d96-848b-1de28c643417:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: __blank__
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: heading
name: Heading
sortOrder: 1
