field: 778abb42-18bd-447c-99ae-483c775ed3bd # Content Blocks
fieldLayouts:
  6f1b2935-dba4-460d-be70-b29a7aa0aa60:
    tabs:
      -
        elements:
          -
            fieldUid: dad3b3bd-ab3c-486d-a552-b3cc718f8e1c # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a65ec270-2111-40c2-bf47-f3d6d929603a # Pre Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f109ee5b-bb41-47ce-aaa0-53b5304e0e22 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3b943244-76d1-4973-9d71-6ec6c109e255 # Sub Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3ad065f3-cd49-4ea6-91e3-12d3a0f0e30f # Text Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 913eb47c-ce43-4325-bb3a-1f5d99065038 # Highlight Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  3ad065f3-cd49-4ea6-91e3-12d3a0f0e30f: # Text Color
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: textColor
    instructions: ''
    name: 'Text Color'
    searchable: true
    settings:
      options:
        -
          __assoc__:
            -
              - default
              - '1'
            -
              - label
              - 'Black Text'
            -
              - value
              - blackText
        -
          __assoc__:
            -
              - default
              - ''
            -
              - label
              - 'White Text'
            -
              - value
              - whiteText
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  3b943244-76d1-4973-9d71-6ec6c109e255: # Sub Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: subHeading
    instructions: ''
    name: 'Sub Heading'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  913eb47c-ce43-4325-bb3a-1f5d99065038: # Highlight Text
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: highlightText
    instructions: 'Will apply a background for the text to increase contrast from the background.'
    name: 'Highlight Text'
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  a65ec270-2111-40c2-bf47-f3d6d929603a: # Pre Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: preHeading
    instructions: ''
    name: 'Pre Heading'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  dad3b3bd-ab3c-486d-a552-b3cc718f8e1c: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:a36fa6aa-4824-448f-82cf-b3086f8582c5' # Images
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:a36fa6aa-4824-448f-82cf-b3086f8582c5' # Images
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  f109ee5b-bb41-47ce-aaa0-53b5304e0e22: # Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: imageAndHeadings
name: 'Image and Headings'
sortOrder: 2
