field: 778abb42-18bd-447c-99ae-483c775ed3bd
fieldLayouts:
  e8d49680-7ba8-48aa-83b6-01f3ddbfe9c4:
    tabs:
      -
        fields:
          4e48185d-8e74-4fa1-b4b4-fdac5ceddf6d:
            required: false
            sortOrder: 1
          11b555a2-89cb-434c-a97c-8bf858a76326:
            required: false
            sortOrder: 4
          13b529cb-1236-4eb5-95a0-e20c2358385e:
            required: false
            sortOrder: 5
          85241ed2-6bbd-4dd0-af5c-07842116ccf3:
            required: false
            sortOrder: 7
          b7672c12-833b-4554-afc9-ec3d68dbd78d:
            required: false
            sortOrder: 3
          e6e6fbf0-a370-48de-b635-6f31bece3c9d:
            required: false
            sortOrder: 6
          f668aa75-41bb-4309-9114-26d72e1547ff:
            required: false
            sortOrder: 2
        name: Content
        sortOrder: 1
fields:
  4e48185d-8e74-4fa1-b4b4-fdac5ceddf6d:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  11b555a2-89cb-434c-a97c-8bf858a76326:
    contentColumnType: string
    fieldGroup: null
    handle: slideImages
    instructions: ''
    name: 'Slide Images'
    searchable: true
    settings:
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:a36fa6aa-4824-448f-82cf-b3086f8582c5'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      restrictFiles: '1'
      selectionLabel: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:a36fa6aa-4824-448f-82cf-b3086f8582c5'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: ''
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  13b529cb-1236-4eb5-95a0-e20c2358385e:
    contentColumnType: string
    fieldGroup: null
    handle: slideEntries
    instructions: ''
    name: 'Slide Entries'
    searchable: true
    settings:
      limit: ''
      localizeRelations: false
      selectionLabel: ''
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: ''
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  85241ed2-6bbd-4dd0-af5c-07842116ccf3:
    contentColumnType: boolean
    fieldGroup: null
    handle: darkUI
    instructions: ''
    name: 'Dark UI'
    searchable: true
    settings:
      default: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  b7672c12-833b-4554-afc9-ec3d68dbd78d:
    contentColumnType: text
    fieldGroup: null
    handle: ctaLinkText
    instructions: ''
    name: 'CTA Link Text'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e6e6fbf0-a370-48de-b635-6f31bece3c9d:
    contentColumnType: boolean
    fieldGroup: null
    handle: slideLayoutCentered
    instructions: 'When enabled it''s best to have 6+ Slide Images/Entries so that the slider will wrap nicely on wide screens.'
    name: 'Slide Layout Centered'
    searchable: true
    settings:
      default: '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  f668aa75-41bb-4309-9114-26d72e1547ff:
    contentColumnType: string
    fieldGroup: null
    handle: ctaLink
    instructions: ''
    name: 'CTA Link'
    searchable: true
    settings:
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: ''
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: slider
name: Slider
sortOrder: 4
