field: 778abb42-18bd-447c-99ae-483c775ed3bd
fieldLayouts:
  b00121d3-e692-4fad-9a4d-14069ec52bf4:
    tabs:
      -
        fields:
          00f86307-b225-423b-bd34-b70af6632cf2:
            required: false
            sortOrder: 3
          2b1996eb-1a60-4257-b4ab-2e41c49fbd06:
            required: false
            sortOrder: 10
          4c127ec9-df18-4d62-bd02-cf8b5044f7ea:
            required: false
            sortOrder: 7
          52ff2568-6318-44d5-a130-818c19f83360:
            required: false
            sortOrder: 5
          5ccbb75b-a9e9-455a-baf9-60aaa799d452:
            required: false
            sortOrder: 9
          5f06df0c-02b7-4b2d-9b75-4b22a09c3a12:
            required: false
            sortOrder: 8
          7cce3872-9055-454a-8fdc-45cbccec785b:
            required: false
            sortOrder: 6
          d10684d5-bcd7-4e35-b0be-69377f981c39:
            required: false
            sortOrder: 1
          eb7b8bc9-c07a-4a25-9201-8174bd70fcb9:
            required: false
            sortOrder: 2
          f466ab59-2e29-4cce-85b8-f9ebe7000b03:
            required: false
            sortOrder: 4
        name: Content
        sortOrder: 1
fields:
  00f86307-b225-423b-bd34-b70af6632cf2:
    contentColumnType: text
    fieldGroup: null
    handle: linkLabel
    instructions: ''
    name: 'Link Label'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  2b1996eb-1a60-4257-b4ab-2e41c49fbd06:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: true
    settings:
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:a36fa6aa-4824-448f-82cf-b3086f8582c5'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: '1'
      selectionLabel: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:a36fa6aa-4824-448f-82cf-b3086f8582c5'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: ''
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  4c127ec9-df18-4d62-bd02-cf8b5044f7ea:
    contentColumnType: text
    fieldGroup: null
    handle: leftStatLabel
    instructions: ''
    name: 'Left Stat Label'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  52ff2568-6318-44d5-a130-818c19f83360:
    contentColumnType: string(255)
    fieldGroup: null
    handle: externalLink
    instructions: ''
    name: 'External Link'
    searchable: true
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  5ccbb75b-a9e9-455a-baf9-60aaa799d452:
    contentColumnType: text
    fieldGroup: null
    handle: rightStatLabel
    instructions: ''
    name: 'Right Stat Label'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  5f06df0c-02b7-4b2d-9b75-4b22a09c3a12:
    contentColumnType: text
    fieldGroup: null
    handle: rightStatValue
    instructions: ''
    name: 'Right Stat Value'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  7cce3872-9055-454a-8fdc-45cbccec785b:
    contentColumnType: text
    fieldGroup: null
    handle: leftStatValue
    instructions: ''
    name: 'Left Stat Value'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d10684d5-bcd7-4e35-b0be-69377f981c39:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  eb7b8bc9-c07a-4a25-9201-8174bd70fcb9:
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: ''
    name: Description
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: VHC-no-assets.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  f466ab59-2e29-4cce-85b8-f9ebe7000b03:
    contentColumnType: string
    fieldGroup: null
    handle: internalLink
    instructions: 'Will override the External Link value if used.'
    name: 'Internal Link'
    searchable: true
    settings:
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: ''
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: statsAndImage
name: 'Stats and Image'
sortOrder: 3
