fieldLayouts:
  435a9c09-fba5-4a0f-99d7-137fe73929f1:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: beb1c87a-67bb-421f-933f-4bc3d1e125e3
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 778abb42-18bd-447c-99ae-483c775ed3bd
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: c8da1bd9-67c9-402f-8a95-aeaec337e207
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 2
handle: contact
hasTitleField: false
name: Contact
section: 8f6c3046-e9ee-4df9-af84-6dc0199f01da
sortOrder: 1
titleFormat: '{section.name|raw}'
