fieldLayouts:
  c266fd55-9906-470d-b73b-a1e12e86bb69:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: beb1c87a-67bb-421f-933f-4bc3d1e125e3
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 778abb42-18bd-447c-99ae-483c775ed3bd
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: c8da1bd9-67c9-402f-8a95-aeaec337e207
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 2
handle: visit
hasTitleField: false
name: Visit
section: 8a02b167-35d9-4c71-bc4b-59ee401246e3
sortOrder: 1
titleFormat: '{section.name|raw}'
