handle: newsCategory
name: 'News Category'
siteSettings:
  beffd6f6-3f04-4ae0-b2c6-71a4e419ab57:
    hasUrls: true
    template: _/pages/news
    uriFormat: 'news/category/{slug}'
  c42694e0-26f4-46d0-9ffe-3e7fe6a64cb9:
    hasUrls: true
    template: _/pages/news
    uriFormat: 'news/category/{slug}'
structure:
  maxLevels: null
  uid: 7e72aa7b-bf24-45c1-96f8-48a62b753660
