dateModified: 1574725382
email:
  fromEmail: sam@craftcms.com
  fromName: 'Demo Starter'
  template: ''
  transportType: craftcms\postmark\Adapter
  transportSettings:
    token: $POSTMARK_API_TOKEN
fieldGroups:
  1bff9c9f-5c93-4679-967d-0f9095c856fa:
    name: Common
fields:
  701ed750-1c7f-4b39-9be6-2c25746f29ba:
    name: 'Image Alt'
    handle: imageAlt
    instructions: ''
    searchable: false
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\PlainText
    settings:
      placeholder: ''
      code: ''
      multiline: ''
      initialRows: '4'
      charLimit: ''
      columnType: text
    contentColumnType: text
    fieldGroup: 1bff9c9f-5c93-4679-967d-0f9095c856fa
plugins:
  aws-s3:
    edition: standard
    enabled: true
    schemaVersion: '1.2'
  dumper:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  colour-swatches:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  freeform:
    edition: lite
    enabled: true
    schemaVersion: 3.0.4
  imager:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  imager-pretransform:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  mix:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  position-fieldtype:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  queue-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  redactor-custom-styles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  seomatic:
    edition: standard
    enabled: true
    schemaVersion: 3.0.8
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  typogrify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.2.0
  postmark:
    edition: standard
    enabled: true
    schemaVersion: 2.0.1
sections:
  9d1ed50c-2239-4171-8b5a-ab121973301f:
    name: Home
    handle: home
    type: single
    enableVersioning: true
    propagationMethod: all
    siteSettings:
      c42694e0-26f4-46d0-9ffe-3e7fe6a64cb9:
        enabledByDefault: true
        hasUrls: true
        uriFormat: __home__
        template: _/pages/home
    entryTypes:
      0b3ab84a-728c-4dfa-b505-ee524b9631d9:
        name: Home
        handle: home
        hasTitleField: false
        titleLabel: null
        titleFormat: '{section.name|raw}'
        sortOrder: 1
siteGroups:
  20d3ac0c-0016-4714-9ce6-ffd91f1a0d5b:
    name: 'Europa Museum'
sites:
  c42694e0-26f4-46d0-9ffe-3e7fe6a64cb9:
    siteGroup: 20d3ac0c-0016-4714-9ce6-ffd91f1a0d5b
    name: Europa
    handle: default
    language: en-US
    hasUrls: true
    baseUrl: $DEFAULT_SITE_URL
    sortOrder: 1
    primary: true
system:
  edition: pro
  name: 'Europa Museum'
  live: true
  schemaVersion: 3.3.3
  timeZone: America/Los_Angeles
users:
  requireEmailVerification: true
  allowPublicRegistration: false
  defaultGroup: null
  photoVolumeUid: null
  photoSubpath: ''
volumes:
  a36fa6aa-4824-448f-82cf-b3086f8582c5:
    name: Images
    handle: images
    type: craft\awss3\Volume
    hasUrls: true
    url: 'https://s3.us-west-2.amazonaws.com/craftcms-client-demos/'
    settings:
      subfolder: europa/images
      keyId: $AWS_ACCESS_KEY_ID
      secret: $AWS_SECRET_ACCESS_KEY
      bucketSelectionMode: choose
      bucket: craftcms-client-demos
      region: us-west-2
      expires: ''
      makeUploadsPublic: '1'
      storageClass: ''
      cfDistributionId: ''
      cfPrefix: ''
      autoFocalPoint: ''
    sortOrder: 1
    fieldLayouts:
      73319165-f289-4758-a3f8-a617823df46f:
        tabs:
          -
            name: Content
            sortOrder: 1
            fields:
              701ed750-1c7f-4b39-9be6-2c25746f29ba:
                required: false
                sortOrder: 1
