dateModified: 1577827398
email:
  fromEmail: sam@craftcms.com
  fromName: 'Demo Starter'
  template: ''
  transportType: craftcms\postmark\Adapter
  transportSettings:
    token: $POSTMARK_API_TOKEN
fieldGroups:
  1bff9c9f-5c93-4679-967d-0f9095c856fa:
    name: Common
  c48ef81e-dcad-417f-a7e7-ed34cac15d46:
    name: Exhibitions
fields:
  701ed750-1c7f-4b39-9be6-2c25746f29ba:
    name: 'Image Alt'
    handle: imageAlt
    instructions: ''
    searchable: false
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\PlainText
    settings:
      placeholder: ''
      code: ''
      multiline: ''
      initialRows: '4'
      charLimit: ''
      columnType: text
    contentColumnType: text
    fieldGroup: 1bff9c9f-5c93-4679-967d-0f9095c856fa
  778abb42-18bd-447c-99ae-483c775ed3bd:
    name: 'Content Blocks'
    handle: contentBlocks
    instructions: ''
    searchable: true
    translationMethod: site
    translationKeyFormat: null
    type: craft\fields\Matrix
    settings:
      minBlocks: ''
      maxBlocks: ''
      contentTable: '{{%matrixcontent_contentblocks}}'
      propagationMethod: all
    contentColumnType: string
    fieldGroup: 1bff9c9f-5c93-4679-967d-0f9095c856fa
  beb1c87a-67bb-421f-933f-4bc3d1e125e3:
    name: 'Hero Image'
    handle: heroImage
    instructions: ''
    searchable: true
    translationMethod: site
    translationKeyFormat: null
    type: craft\fields\Assets
    settings:
      useSingleFolder: ''
      defaultUploadLocationSource: 'volume:a36fa6aa-4824-448f-82cf-b3086f8582c5'
      defaultUploadLocationSubpath: exhibitions/
      singleUploadLocationSource: 'volume:a36fa6aa-4824-448f-82cf-b3086f8582c5'
      singleUploadLocationSubpath: ''
      restrictFiles: '1'
      allowedKinds:
        - image
      sources:
        - 'volume:a36fa6aa-4824-448f-82cf-b3086f8582c5'
      source: null
      targetSiteId: null
      viewMode: large
      limit: '1'
      selectionLabel: 'Add an image'
      localizeRelations: false
      validateRelatedElements: ''
    contentColumnType: string
    fieldGroup: c48ef81e-dcad-417f-a7e7-ed34cac15d46
matrixBlockTypes:
  0d3f8f65-dde1-4921-a575-26ade4545fc9:
    field: 778abb42-18bd-447c-99ae-483c775ed3bd
    name: 'Entry Slider'
    handle: entrySlider
    sortOrder: 2
    fields:
      13b529cb-1236-4eb5-95a0-e20c2358385e:
        name: 'Slide Entries'
        handle: slideEntries
        instructions: ''
        searchable: true
        translationMethod: site
        translationKeyFormat: null
        type: craft\fields\Entries
        settings:
          sources: '*'
          source: null
          targetSiteId: null
          viewMode: null
          limit: ''
          selectionLabel: ''
          localizeRelations: false
          validateRelatedElements: ''
        contentColumnType: string
        fieldGroup: null
      4e48185d-8e74-4fa1-b4b4-fdac5ceddf6d:
        name: Heading
        handle: heading
        instructions: ''
        searchable: true
        translationMethod: none
        translationKeyFormat: null
        type: craft\fields\PlainText
        settings:
          placeholder: ''
          code: ''
          multiline: ''
          initialRows: '4'
          charLimit: ''
          columnType: text
        contentColumnType: text
        fieldGroup: null
      b7672c12-833b-4554-afc9-ec3d68dbd78d:
        name: 'CTA Link Text'
        handle: ctaLinkText
        instructions: ''
        searchable: true
        translationMethod: none
        translationKeyFormat: null
        type: craft\fields\PlainText
        settings:
          placeholder: ''
          code: ''
          multiline: ''
          initialRows: '4'
          charLimit: ''
          columnType: text
        contentColumnType: text
        fieldGroup: null
      f668aa75-41bb-4309-9114-26d72e1547ff:
        name: 'CTA Link'
        handle: ctaLink
        instructions: ''
        searchable: true
        translationMethod: site
        translationKeyFormat: null
        type: craft\fields\Entries
        settings:
          sources: '*'
          source: null
          targetSiteId: null
          viewMode: null
          limit: '1'
          selectionLabel: ''
          localizeRelations: false
          validateRelatedElements: ''
        contentColumnType: string
        fieldGroup: null
    fieldLayouts:
      e8d49680-7ba8-48aa-83b6-01f3ddbfe9c4:
        tabs:
          -
            name: Content
            sortOrder: 1
            fields:
              13b529cb-1236-4eb5-95a0-e20c2358385e:
                required: false
                sortOrder: 4
              4e48185d-8e74-4fa1-b4b4-fdac5ceddf6d:
                required: false
                sortOrder: 3
              b7672c12-833b-4554-afc9-ec3d68dbd78d:
                required: false
                sortOrder: 1
              f668aa75-41bb-4309-9114-26d72e1547ff:
                required: false
                sortOrder: 2
  83ef9ed9-6360-4f64-abbb-920baeb2048e:
    field: 778abb42-18bd-447c-99ae-483c775ed3bd
    name: Exhibit
    handle: exhibit
    sortOrder: 1
    fields:
      6c31cab7-7f79-4628-b345-9a700a16a726:
        name: Exhibit
        handle: exhibit
        instructions: ''
        searchable: true
        translationMethod: site
        translationKeyFormat: null
        type: craft\fields\Entries
        settings:
          sources: '*'
          source: null
          targetSiteId: null
          viewMode: null
          limit: '1'
          selectionLabel: 'Add an Exhibit'
          localizeRelations: false
          validateRelatedElements: ''
        contentColumnType: string
        fieldGroup: null
      8df6d29d-59a0-44ee-80e5-f69849956547:
        name: 'Text Color'
        handle: textColor
        instructions: ''
        searchable: true
        translationMethod: none
        translationKeyFormat: null
        type: craft\fields\RadioButtons
        settings:
          options:
            -
              label: 'Black Text'
              value: blackText
              default: '1'
            -
              label: 'White Text'
              value: whiteText
              default: ''
        contentColumnType: string
        fieldGroup: null
    fieldLayouts:
      317b7d36-2f97-4ffa-846f-0404ab3c6df8:
        tabs:
          -
            name: Content
            sortOrder: 1
            fields:
              6c31cab7-7f79-4628-b345-9a700a16a726:
                required: false
                sortOrder: 1
              8df6d29d-59a0-44ee-80e5-f69849956547:
                required: false
                sortOrder: 2
plugins:
  aws-s3:
    edition: standard
    enabled: true
    schemaVersion: '1.2'
  dumper:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  colour-swatches:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  freeform:
    edition: lite
    enabled: true
    schemaVersion: 3.0.5
  imager:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  imager-pretransform:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  mix:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  position-fieldtype:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  queue-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  redactor-custom-styles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  seomatic:
    edition: standard
    enabled: true
    schemaVersion: 3.0.8
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  typogrify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.2.1
  postmark:
    edition: standard
    enabled: true
    schemaVersion: 2.0.1
sections:
  0edb3240-3f53-4f13-a789-2bd0b6cae755:
    name: Styleguide
    handle: styleguide
    type: single
    enableVersioning: true
    propagationMethod: all
    siteSettings:
      c42694e0-26f4-46d0-9ffe-3e7fe6a64cb9:
        enabledByDefault: true
        hasUrls: true
        uriFormat: styleguide
        template: _/pages/styleguide
    entryTypes:
      03ad2302-4a79-4d90-91f8-bb515f0157d0:
        name: Styleguide
        handle: styleguide
        hasTitleField: false
        titleLabel: null
        titleFormat: '{section.name|raw}'
        sortOrder: 1
  9d1ed50c-2239-4171-8b5a-ab121973301f:
    name: Home
    handle: home
    type: single
    enableVersioning: true
    propagationMethod: all
    siteSettings:
      c42694e0-26f4-46d0-9ffe-3e7fe6a64cb9:
        enabledByDefault: true
        hasUrls: true
        uriFormat: __home__
        template: _/pages/home
    entryTypes:
      0b3ab84a-728c-4dfa-b505-ee524b9631d9:
        name: Home
        handle: home
        hasTitleField: false
        titleLabel: ''
        titleFormat: '{section.name|raw}'
        sortOrder: 1
        fieldLayouts:
          e1fad73a-2e23-4fa8-8f33-5037fe6b6d76:
            tabs:
              -
                name: Content
                sortOrder: 1
                fields:
                  778abb42-18bd-447c-99ae-483c775ed3bd:
                    required: false
                    sortOrder: 1
  c49dac11-102e-429e-8bcc-5c8d99508dcb:
    name: Exhibitions
    handle: exhibitions
    type: structure
    enableVersioning: true
    propagationMethod: all
    siteSettings:
      c42694e0-26f4-46d0-9ffe-3e7fe6a64cb9:
        enabledByDefault: true
        hasUrls: true
        uriFormat: 'exhibitions/{slug}'
        template: _/pages/exhibit
    structure:
      uid: 0410f32e-7831-41b2-bd6f-cb90cc47e1aa
      maxLevels: 1
    entryTypes:
      13b5cd9c-c5b1-40bb-8a8a-dc14815aabad:
        name: Exhibitions
        handle: exhibitions
        hasTitleField: true
        titleLabel: Title
        titleFormat: ''
        sortOrder: 1
        fieldLayouts:
          268b8d62-05d6-417a-9a6b-ed707ea8dd4b:
            tabs:
              -
                name: Content
                sortOrder: 1
                fields:
                  beb1c87a-67bb-421f-933f-4bc3d1e125e3:
                    required: false
                    sortOrder: 1
siteGroups:
  20d3ac0c-0016-4714-9ce6-ffd91f1a0d5b:
    name: 'Europa Museum'
sites:
  c42694e0-26f4-46d0-9ffe-3e7fe6a64cb9:
    siteGroup: 20d3ac0c-0016-4714-9ce6-ffd91f1a0d5b
    name: europa.museum
    handle: default
    language: en-US
    hasUrls: true
    baseUrl: $DEFAULT_SITE_URL
    sortOrder: 1
    primary: true
system:
  edition: pro
  name: 'Europa Museum'
  live: true
  schemaVersion: 3.3.3
  timeZone: America/Los_Angeles
users:
  requireEmailVerification: true
  allowPublicRegistration: false
  defaultGroup: null
  photoVolumeUid: null
  photoSubpath: ''
volumes:
  a36fa6aa-4824-448f-82cf-b3086f8582c5:
    name: Images
    handle: images
    type: craft\awss3\Volume
    hasUrls: true
    url: 'https://s3.us-west-2.amazonaws.com/craftcms-client-demos/'
    settings:
      subfolder: europa/images
      keyId: $AWS_ACCESS_KEY_ID
      secret: $AWS_SECRET_ACCESS_KEY
      bucketSelectionMode: choose
      bucket: craftcms-client-demos
      region: us-west-2
      expires: ''
      makeUploadsPublic: '1'
      storageClass: ''
      cfDistributionId: ''
      cfPrefix: ''
      autoFocalPoint: ''
    sortOrder: 1
    fieldLayouts:
      73319165-f289-4758-a3f8-a617823df46f:
        tabs:
          -
            name: Content
            sortOrder: 1
            fields:
              701ed750-1c7f-4b39-9be6-2c25746f29ba:
                required: false
                sortOrder: 1
