fieldLayouts:
  73319165-f289-4758-a3f8-a617823df46f:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
          -
            fieldUid: 701ed750-1c7f-4b39-9be6-2c25746f29ba
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8b592bee-c976-4c83-be76-d749cc991410
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: images
hasUrls: true
name: Images
settings:
  addSubfolderToRootUrl: true
  autoFocalPoint: ''
  bucket: $AWS_IMAGES_BUCKET
  bucketSelectionMode: manual
  cfDistributionId: ''
  cfPrefix: ''
  expires: ''
  keyId: $AWS_ACCESS_KEY_ID
  makeUploadsPublic: '1'
  region: $AWS_REGION
  secret: $AWS_SECRET_ACCESS_KEY
  storageClass: ''
  subfolder: $AWS_IMAGES_SUBFOLDER
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
type: craft\awss3\Volume
url: $AWS_BASE_URL
