contentColumnType: text
fieldGroup: 1bff9c9f-5c93-4679-967d-0f9095c856fa # Common
handle: imageCaption
instructions: 'Format: "Title" — 2020, Author Name'
name: 'Image Caption'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
