columnSuffix: null
contentColumnType: string
fieldGroup: f1b24b40-32c4-47c3-859d-21dd41bbe6f4 # Globals
handle: linksRight
instructions: ''
name: 'Links - Right'
searchable: true
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
