enableVersioning: true
handle: visit
name: Visit
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  c42694e0-26f4-46d0-9ffe-3e7fe6a64cb9:
    enabledByDefault: true
    hasUrls: true
    template: _/pages/visit
    uriFormat: visit
type: single
